Repository ucsb-cs156-s25/proj-frontiers-s25-12, pull requests merged in 2025-05, with the labels that each got.

#32 mw - Add Fixtures for RosterStudents
  frontend/src/fixtures/rosterStudentsFixtures.js
Labels: 5, Merge Candidate-CI

#30 jj - BACKEND - Add delete for roster student
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/Course.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10, Merge Candidate-CI

#28 Create Instructor Table (entity and repository)
  src/main/java/edu/ucsb/cs156/frontiers/entities/Instructor.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/InstructorRepository.java
  src/main/resources/db/migration/changes/007-create-Instructors.json
Labels: 5, Merge Candidate-CI

#34 aw - Adds update to RosterStudent. Also adds a check for duplicate studentId in Create
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10, Merge Candidate-CI, Ready-For-Staff

#36 Added controller for students to see courses they are enrolled in
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: 10, Merge Candidate-CI

#37 hk - CREATE Admin Table
  src/main/java/edu/ucsb/cs156/frontiers/entities/Admin.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/AdminRepository.java
  src/main/resources/db/migration/changes/008-Admins-create.json
Labels: 5, Merge Candidate-CI

#33 mw - Add table component for RosterStudents plus stories and tests
  frontend/src/main/components/RosterStudents/RosterStudentsTable.js
  frontend/src/main/utils/rosterStudentUtils.js
  frontend/src/stories/components/RosterStudents/RosterStudentsTable.stories.js
  frontend/src/tests/components/RosterStudents/RosterStudentsTable.test.js
  frontend/src/tests/utils/rosterStudentUtils.test.js
Labels: 10

#40 jj - Create RoleEmailTable for Admin and Instructors
  frontend/src/main/components/Users/RoleEmailForm.js
  frontend/src/main/components/Users/RoleEmailTable.js
  frontend/src/main/utils/RoleEmailUtils.js
  frontend/src/stories/components/Users/RoleEmailTable.stories.js
  frontend/src/tests/components/Users/RoleEmailTable.test.js
  frontend/src/tests/utils/RoleEmailUtils.test.js
Labels: 10, Merge Candidate-CI

#44 hk - FEATURE - ADMIN_EMAILS are added to the admins table at startup. #6
  src/main/java/edu/ucsb/cs156/frontiers/startup/FrontiersApplicationRunner.java
  src/main/java/edu/ucsb/cs156/frontiers/startup/FrontiersStartup.java
  src/test/java/edu/ucsb/cs156/frontiers/startup/FrontiersApplicationRunnerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/startup/FrontiersStartupTests.java
Labels: 10, Merge Candidate-CI

#43 simony05 - added controller for students to see courses where they are staff in
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CourseStaffController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
Labels: 10, Merge Candidate-CI
